-- 1. ADD COLUMNS IF NOT EXISTS (Safety measure)
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS role TEXT DEFAULT 'user';
ALTER TABLE public.levels ADD COLUMN IF NOT EXISTS yield_rate DECIMAL(6,5) DEFAULT 1.0;

-- 2. SET FIRST USER TO ADMIN
UPDATE public.profiles 
SET role = 'admin', is_admin = true
WHERE id = (SELECT id FROM public.profiles ORDER BY created_at ASC LIMIT 1);

-- 3. RESET LEVELS & TASKS
TRUNCATE TABLE public.user_tasks CASCADE;
TRUNCATE TABLE public.task_items RESTART IDENTITY CASCADE;
DELETE FROM public.levels;

-- 4. INSERT CORRECT LEVELS (JUNIOR, ASSOCIATE, ETC)
INSERT INTO public.levels (id, name, price, commission_rate, yield_rate, tasks_per_set, sets_per_day, description)
VALUES 
(1, 'Junior Node', 0, 0.005, 1.0, 40, 3, 'Initial entry-level market node for basic sequence processing.'),
(2, 'Associate Node', 200, 0.006, 1.2, 45, 3, 'Enhanced node with increased yield multipliers and priority matching.'),
(3, 'Senior Node', 500, 0.007, 1.5, 50, 3, 'Professional-grade terminal for high-frequency market vector analysis.'),
(4, 'Elite Node', 1500, 0.008, 1.8, 55, 3, 'Advanced neural architecture for institutional optimization sequences.'),
(5, 'Ultimate Node', 3000, 0.010, 2.5, 60, 3, 'Unrestricted node access with peak performance and total yield saturation.');

-- 5. INSERT DYNAMIC TASKS FOR ALL 5 LEVELS
INSERT INTO public.task_items (title, image_url, category, description, level_id)
VALUES
('Quantum Series X 825 - Junior', '/items/premium/c4fb2a3010c21316876f29d145611d01.jpg', 'Fashion', 'Advanced market node optimization for the Fashion sector. Tier 1 authorization. Unit #1.', 1),
('Catalyst Pro 826 - Junior', '/items/premium/neck-chains.jpg', 'Finance', 'Advanced market node optimization for the Finance sector. Tier 1 authorization. Unit #2.', 1),
('Modern Era 397 - Junior', '/items/premium/51wCsmJcmAL._AC_UL400_.jpg', 'Home', 'Advanced market node optimization for the Home sector. Tier 1 authorization. Unit #3.', 1),
('Apex Prime Edition 622 - Junior', '/items/premium/71-vB5wiVCL.jpg', 'Strategic', 'Advanced market node optimization for the Strategic sector. Tier 1 authorization. Unit #4.', 1),
('Prism Dynamic 608 - Junior', '/items/premium/arrangement-car-tires-style-frontal-perspective_46383-22376.jpg', 'Luxury', 'Advanced market node optimization for the Luxury sector. Tier 1 authorization. Unit #5.', 1),
('Vector Prime 379 - Junior', '/items/premium/AIR+FORCE+1+BG.png', 'Electronics', 'Advanced market node optimization for the Electronics sector. Tier 1 authorization. Unit #6.', 1),
('Spectrum Glow 692 - Junior', '/items/premium/Comparing-Prescription-And-Non-Prescription-Reading-Glasses-1.jpg', 'Strategic', 'Advanced market node optimization for the Strategic sector. Tier 1 authorization. Unit #7.', 1),
('Spectrum Glow 892 - Junior', '/items/premium/de96e5dbcb096b19f7ff4078bc92b2f4.jpg', 'Health', 'Advanced market node optimization for the Health sector. Tier 1 authorization. Unit #8.', 1),
('Stellar Edge 742 - Junior', '/items/premium/226613-muslher-pijama-mujer-algodon-estampado-01.jpg', 'Home', 'Advanced market node optimization for the Home sector. Tier 1 authorization. Unit #9.', 1),
('Nova Star 266 - Junior', '/items/premium/Trie-Small-Dining-Table-in-Calgary5.jpg', 'Finance', 'Advanced market node optimization for the Finance sector. Tier 1 authorization. Unit #10.', 1),
('Chrono Master 469 - Junior', '/items/premium/Sc2a3d6125ebe4ef2bd30c2e40fd3bf11U.jpg', 'Health', 'Advanced market node optimization for the Health sector. Tier 1 authorization. Unit #11.', 1),
('Prime Focus 960 - Junior', '/items/premium/Style-Jaket-Bomber-Pria-Terbaru.jpg', 'Finance', 'Advanced market node optimization for the Finance sector. Tier 1 authorization. Unit #12.', 1),
('Diamond Edge 146 - Junior', '/items/premium/85c64-iso2.png', 'Beauty', 'Advanced market node optimization for the Beauty sector. Tier 1 authorization. Unit #13.', 1),
('Retro Vibe 699 - Junior', '/items/premium/NIKE+VOMERO+18-001.png', 'Beauty', 'Advanced market node optimization for the Beauty sector. Tier 1 authorization. Unit #14.', 1),
('Premium Executive Suite 901 - Junior', '/items/premium/tdhW8QyiAaZKLvf7Y6SzPD.jpg', 'Automotive', 'Advanced market node optimization for the Automotive sector. Tier 1 authorization. Unit #15.', 1),
('Omni Vision Pro 485 - Junior', '/items/premium/1-optima-car-battery-brand.jpg', 'Automotive', 'Advanced market node optimization for the Automotive sector. Tier 1 authorization. Unit #16.', 1),
('Echo Pulse 279 - Junior', '/items/premium/816Vz-wcbsL.jpg', 'Luxury', 'Advanced market node optimization for the Luxury sector. Tier 1 authorization. Unit #17.', 1),
('Steel Guard 407 - Junior', '/items/premium/51f5QRoqZIL._AC_UY1100_.jpg', 'Strategic', 'Advanced market node optimization for the Strategic sector. Tier 1 authorization. Unit #18.', 1),
('Flux Capacitor 794 - Junior', '/items/premium/IMG_2978.jpg', 'Home', 'Advanced market node optimization for the Home sector. Tier 1 authorization. Unit #19.', 1),
('Premium Executive Suite 238 - Junior', '/items/premium/1-500x500.jpg', 'Strategic', 'Advanced market node optimization for the Strategic sector. Tier 1 authorization. Unit #20.', 1),
('Pulse Beat 348 - Junior', '/items/premium/makeup-products-studio-shot-cosmetics-studio-background-floating-eye-shadows-lipstick-closeup-shot_723234-5463.jpg', 'Fashion', 'Advanced market node optimization for the Fashion sector. Tier 1 authorization. Unit #21.', 1),
('Synapse Net 840 - Junior', '/items/premium/North-1-2-min-1-683x1024.png', 'Electronics', 'Advanced market node optimization for the Electronics sector. Tier 1 authorization. Unit #22.', 1),
('Omni Vision Pro 780 - Junior', '/items/premium/Smart-WC.png', 'Home', 'Advanced market node optimization for the Home sector. Tier 1 authorization. Unit #23.', 1),
('Oasis Mist 218 - Junior', '/items/premium/43-INCH-4K-GOOGLE-TV.jpeg', 'Electronics', 'Advanced market node optimization for the Electronics sector. Tier 1 authorization. Unit #24.', 1),
('Spectrum Glow 536 - Junior', '/items/premium/ladies-pajama-1000x1000.jpg', 'Health', 'Advanced market node optimization for the Health sector. Tier 1 authorization. Unit #25.', 1),
('Horizon Vista 800 - Junior', '/items/premium/microphone.jpg', 'Luxury', 'Advanced market node optimization for the Luxury sector. Tier 1 authorization. Unit #26.', 1),
('Premium Executive Suite 478 - Junior', '/items/premium/il_fullxfull.1664271896_8smg.jpg', 'Beauty', 'Advanced market node optimization for the Beauty sector. Tier 1 authorization. Unit #27.', 1),
('Premium Executive Suite 495 - Junior', '/items/premium/M+NIKE+METCON+10-002.png', 'Strategic', 'Advanced market node optimization for the Strategic sector. Tier 1 authorization. Unit #28.', 1),
('Stellar Edge 275 - Junior', '/items/premium/walmarts-everstart-brand-has-lots-of-support-1740999867.jpg', 'Luxury', 'Advanced market node optimization for the Luxury sector. Tier 1 authorization. Unit #29.', 1),
('Arc Light 219 - Junior', '/items/premium/ya136363.jpg', 'Health', 'Advanced market node optimization for the Health sector. Tier 1 authorization. Unit #30.', 1),
('Catalyst Pro 886 - Junior', '/items/premium/09540b1ec0a03a67bbebb28f1c9c1a74.jpg', 'Beauty', 'Advanced market node optimization for the Beauty sector. Tier 1 authorization. Unit #31.', 1),
('Peak Precision 200 - Junior', '/items/premium/lifee01logocopy.jpg', 'Fashion', 'Advanced market node optimization for the Fashion sector. Tier 1 authorization. Unit #32.', 1),
('Infinity Loop 126 - Junior', '/items/premium/d6e3064397ae451ee25e529404de041d.jpg', 'Electronics', 'Advanced market node optimization for the Electronics sector. Tier 1 authorization. Unit #33.', 1),
('Zenith Peak 340 - Junior', '/items/premium/budgetdigitalpiano-2048px-3635.jpg', 'Strategic', 'Advanced market node optimization for the Strategic sector. Tier 1 authorization. Unit #34.', 1),
('Aura Glow 281 - Junior', '/items/premium/c17ad85f43d97d31e559b8e723a50d72.jpg', 'Automotive', 'Advanced market node optimization for the Automotive sector. Tier 1 authorization. Unit #35.', 1),
('Steel Guard 433 - Junior', '/items/premium/713o7zCiaJL.jpg', 'Home', 'Advanced market node optimization for the Home sector. Tier 1 authorization. Unit #36.', 1),
('Omni Vision Pro 634 - Junior', '/items/premium/HighSecurityDoorDisplay.jpg', 'Home', 'Advanced market node optimization for the Home sector. Tier 1 authorization. Unit #37.', 1),
('Spectrum Glow 978 - Junior', '/items/premium/93a8dc69d565e9dafd5baab8da71159d7dce0b49-2560x1075.jpg', 'Automotive', 'Advanced market node optimization for the Automotive sector. Tier 1 authorization. Unit #38.', 1),
('Infinity Loop 439 - Junior', '/items/premium/french-door-refrigerator-2048px-LRFLC2706S-3x2-1.jpg', 'Luxury', 'Advanced market node optimization for the Luxury sector. Tier 1 authorization. Unit #39.', 1),
('Grand Master 570 - Junior', '/items/premium/0000569812_961331_09.jpg', 'Fashion', 'Advanced market node optimization for the Fashion sector. Tier 1 authorization. Unit #40.', 1),
('Legacy Gold 518 - Associate', '/items/premium/2338.png', 'Fashion', 'Advanced market node optimization for the Fashion sector. Tier 2 authorization. Unit #1.', 2),
('Chrono Master 438 - Associate', '/items/premium/il_fullxfull.2199507516_pza1.jpg', 'Health', 'Advanced market node optimization for the Health sector. Tier 2 authorization. Unit #2.', 2),
('Catalyst Pro 182 - Associate', '/items/premium/W+NIKE+V2K+RUN-002.png', 'Beauty', 'Advanced market node optimization for the Beauty sector. Tier 2 authorization. Unit #3.', 2),
('Prism Dynamic 312 - Associate', '/items/premium/young-attractive-tired-brunette-man-in-white-t-shirt-sitting-on-bed-with-eyeglasses-in-hand-thoughtfully-working-on-laptop-at-home-2C7J5GD.jpg', 'Automotive', 'Advanced market node optimization for the Automotive sector. Tier 2 authorization. Unit #4.', 2),
('Solaris Ultra 264 - Associate', '/items/premium/Yeah-Mens-Watch-Black-004-1.jpg', 'Electronics', 'Advanced market node optimization for the Electronics sector. Tier 2 authorization. Unit #5.', 2),
('Synapse Net 496 - Associate', '/items/premium/dc08406ad618fb062f21548bb40f1de4_1772901935.png', 'Luxury', 'Advanced market node optimization for the Luxury sector. Tier 2 authorization. Unit #6.', 2),
('Fusion Core 249 - Associate', '/items/premium/A31A3-Rave3S_723e3dcd-24e2-4483-800e-80822d40bb27.png', 'Beauty', 'Advanced market node optimization for the Beauty sector. Tier 2 authorization. Unit #7.', 2),
('Quantum Series X 126 - Associate', '/items/premium/d7ee5acb-e9e9-44aa-bfa2-9abae25abff6.jpg', 'Strategic', 'Advanced market node optimization for the Strategic sector. Tier 2 authorization. Unit #8.', 2),
('Vector Prime 406 - Associate', '/items/premium/studio-microphone-setup-stockcake.jpg', 'Strategic', 'Advanced market node optimization for the Strategic sector. Tier 2 authorization. Unit #9.', 2),
('Origin Base 596 - Associate', '/items/premium/EverStart-Plus-Lead-Acid-Automotive-Battery-Group-Size-96R-12-Volt-590-CCA_06721abc-c58e-4361-b3be-b7ddc447bdbe.4cc0122c93f608d462c03736cbaa2344.jpeg', 'Luxury', 'Advanced market node optimization for the Luxury sector. Tier 2 authorization. Unit #10.', 2),
('Classic Chic 211 - Associate', '/items/premium/1_6f954d2c-0bcf-4e40-a7e6-03db90882e80.jpg', 'Home', 'Advanced market node optimization for the Home sector. Tier 2 authorization. Unit #11.', 2),
('Horizon Vista 264 - Associate', '/items/premium/delton10x_1.png', 'Finance', 'Advanced market node optimization for the Finance sector. Tier 2 authorization. Unit #12.', 2),
('Chrono Master 740 - Associate', '/items/premium/tb-image_share_1711471217415_jpg.png', 'Finance', 'Advanced market node optimization for the Finance sector. Tier 2 authorization. Unit #13.', 2),
('Gold Standard 977 - Associate', '/items/premium/ladies-pyjama-1000x1000.jpg', 'Beauty', 'Advanced market node optimization for the Beauty sector. Tier 2 authorization. Unit #14.', 2),
('Synapse Net 385 - Associate', '/items/premium/3906_06180557274110397.jpeg', 'Health', 'Advanced market node optimization for the Health sector. Tier 2 authorization. Unit #15.', 2),
('Diamond Edge 705 - Associate', '/items/premium/Hg2-4-1024x1024.jpg', 'Luxury', 'Advanced market node optimization for the Luxury sector. Tier 2 authorization. Unit #16.', 2),
('Arc Light 676 - Associate', '/items/premium/14-002.jpg', 'Finance', 'Advanced market node optimization for the Finance sector. Tier 2 authorization. Unit #17.', 2),
('Nebula Smart Node 851 - Associate', '/items/premium/freddie-engineered-wood-wall-mount-dressing-table-mirror-with-shelves-side.jpg', 'Automotive', 'Advanced market node optimization for the Automotive sector. Tier 2 authorization. Unit #18.', 2),
('Premium Executive Suite 921 - Associate', '/items/premium/car-tire-product-photography_950558-12781.jpg', 'Home', 'Advanced market node optimization for the Home sector. Tier 2 authorization. Unit #19.', 2),
('Pulse Beat 216 - Associate', '/items/premium/JKPRAS98-G01V-166708-1400px-1820px.jpg', 'Home', 'Advanced market node optimization for the Home sector. Tier 2 authorization. Unit #20.', 2),
('Premium Executive Suite 935 - Associate', '/items/premium/ladies-cotton-printed-pajamas-nightwear-1000x1000.jpg', 'Home', 'Advanced market node optimization for the Home sector. Tier 2 authorization. Unit #21.', 2),
('Vanguard Leather Bound 290 - Associate', '/items/premium/91sGuTqHYPL._AC_UF894,1000_QL80_.jpg', 'Fashion', 'Advanced market node optimization for the Fashion sector. Tier 2 authorization. Unit #22.', 2),
('Apex Prime Edition 356 - Associate', '/items/premium/e133ef03b5a963f5ed84a0e563eac723.png', 'Luxury', 'Advanced market node optimization for the Luxury sector. Tier 2 authorization. Unit #23.', 2),
('Arc Light 392 - Associate', '/items/premium/51t3M6+tpfL._SL500_.jpg', 'Fashion', 'Advanced market node optimization for the Fashion sector. Tier 2 authorization. Unit #24.', 2),
('Modern Era 696 - Associate', '/items/premium/closeup-of-an-electric-guitar-ACY0AY.jpg', 'Electronics', 'Advanced market node optimization for the Electronics sector. Tier 2 authorization. Unit #25.', 2),
('Pure Silk 494 - Associate', '/items/premium/NIKE+VOMERO+18+(GS).png', 'Strategic', 'Advanced market node optimization for the Strategic sector. Tier 2 authorization. Unit #26.', 2),
('Classic Chic 212 - Associate', '/items/premium/266b4290.png', 'Beauty', 'Advanced market node optimization for the Beauty sector. Tier 2 authorization. Unit #27.', 2),
('Cyber Core 749 - Associate', '/items/premium/arrangement-car-tires-style-frontal-perspective_983424-17658.jpg', 'Automotive', 'Advanced market node optimization for the Automotive sector. Tier 2 authorization. Unit #28.', 2),
('Apex Prime Edition 508 - Associate', '/items/premium/farm_sink_kitchen_ideas__drop_in_acrylic_farmhouse.jpg', 'Fashion', 'Advanced market node optimization for the Fashion sector. Tier 2 authorization. Unit #29.', 2),
('Zenith Peak 830 - Associate', '/items/premium/pijama-velour-spiderman-azul-001.jpg', 'Electronics', 'Advanced market node optimization for the Electronics sector. Tier 2 authorization. Unit #30.', 2),
('Solaris Ultra 241 - Associate', '/items/premium/yamaha-psr-e373-digital-piano-a-professional-keyboard-made-for-everyone-620666177302005995645818-c.jpg', 'Luxury', 'Advanced market node optimization for the Luxury sector. Tier 2 authorization. Unit #31.', 2),
('Element Zero 249 - Associate', '/items/premium/NIKE+VOMERO+18-005.png', 'Electronics', 'Advanced market node optimization for the Electronics sector. Tier 2 authorization. Unit #32.', 2),
('Grand Master 205 - Associate', '/items/premium/51nP5hcOKqL._SL500_.jpg', 'Beauty', 'Advanced market node optimization for the Beauty sector. Tier 2 authorization. Unit #33.', 2),
('Catalyst Pro 943 - Associate', '/items/premium/Sc2d77d30d0184a9784c163c1bca9a06ei.jpg', 'Fashion', 'Advanced market node optimization for the Fashion sector. Tier 2 authorization. Unit #34.', 2),
('Synapse Net 792 - Associate', '/items/premium/Rockville-RPB25-Bluetooth-Speaker-For-iPhone-Android-Laptop-w-USB-SD-Aux-In-FM_71347464-a12c-4a85-a751-e08a74bc83af.f8b1be5771155d8709130b330593c682.jpeg', 'Beauty', 'Advanced market node optimization for the Beauty sector. Tier 2 authorization. Unit #35.', 2),
('Premium Executive Suite 572 - Associate', '/items/premium/C7010-S_102.jpg', 'Home', 'Advanced market node optimization for the Home sector. Tier 2 authorization. Unit #36.', 2),
('Echo Pulse 225 - Associate', '/items/premium/ANNELE-1927_3.jpg', 'Fashion', 'Advanced market node optimization for the Fashion sector. Tier 2 authorization. Unit #37.', 2),
('Cyber Core 146 - Associate', '/items/premium/pvc-sliding-wardrobe-1000x1000.jpg', 'Strategic', 'Advanced market node optimization for the Strategic sector. Tier 2 authorization. Unit #38.', 2),
('Modern Era 187 - Associate', '/items/premium/grey-lh-security-steel-door.jpg', 'Strategic', 'Advanced market node optimization for the Strategic sector. Tier 2 authorization. Unit #39.', 2),
('Luxe Crystal 800 - Associate', '/items/premium/0HDZz.jpg', 'Health', 'Advanced market node optimization for the Health sector. Tier 2 authorization. Unit #40.', 2),
('Cyber Core 342 - Associate', '/items/premium/1ca10c4d14cd-monsoon-wedding-dress.jpg', 'Beauty', 'Advanced market node optimization for the Beauty sector. Tier 2 authorization. Unit #41.', 2),
('Arc Light 605 - Associate', '/items/premium/bb8fce778227b76019252f581f.jpg', 'Fashion', 'Advanced market node optimization for the Fashion sector. Tier 2 authorization. Unit #42.', 2),
('Stellar Edge 451 - Associate', '/items/premium/Photoroom_20260102_195757.png', 'Finance', 'Advanced market node optimization for the Finance sector. Tier 2 authorization. Unit #43.', 2),
('Prism Dynamic 593 - Associate', '/items/premium/il_1080xN.4896222924_mwcz.jpg', 'Finance', 'Advanced market node optimization for the Finance sector. Tier 2 authorization. Unit #44.', 2),
('Arc Light 791 - Associate', '/items/premium/battery-supercharge-offer-march-april-2026_96e983ba-7f53-43da-8bb8-dc0c07bbac82.jpg', 'Health', 'Advanced market node optimization for the Health sector. Tier 2 authorization. Unit #45.', 2),
('Velocity Max 349 - Senior', '/items/premium/NIKE+VOMERO+18-002.png', 'Finance', 'Advanced market node optimization for the Finance sector. Tier 3 authorization. Unit #1.', 3),
('Gold Standard 182 - Senior', '/items/premium/DSC_9404.jpg', 'Electronics', 'Advanced market node optimization for the Electronics sector. Tier 3 authorization. Unit #2.', 3),
('Horizon Plus 657 - Senior', '/items/premium/USB-Game-Steering-Racing-Wheel-Joystick-for-PC.jpg', 'Finance', 'Advanced market node optimization for the Finance sector. Tier 3 authorization. Unit #3.', 3),
('Gold Standard 660 - Senior', '/items/premium/Artboard1_c48e07a1-d9e6-4ce3-85d0-951a0a7c83a1.jpg', 'Home', 'Advanced market node optimization for the Home sector. Tier 3 authorization. Unit #4.', 3),
('Cyber Core 439 - Senior', '/items/premium/11-4108-00_01.jpg', 'Beauty', 'Advanced market node optimization for the Beauty sector. Tier 3 authorization. Unit #5.', 3),
('Arc Light 296 - Senior', '/items/premium/18K-Gold-Wedding-Engagement-Ring-Set-Img-1.jpg', 'Electronics', 'Advanced market node optimization for the Electronics sector. Tier 3 authorization. Unit #6.', 3),
('Arc Light 857 - Senior', '/items/premium/2688_ny1.jpg', 'Luxury', 'Advanced market node optimization for the Luxury sector. Tier 3 authorization. Unit #7.', 3),
('Nebula Smart Node 205 - Senior', '/items/premium/84f3a30ed5c149c74cce518d500fb421.jpg', 'Finance', 'Advanced market node optimization for the Finance sector. Tier 3 authorization. Unit #8.', 3),
('Modern Era 347 - Senior', '/items/premium/il_340x270.4378007574_dlkf.jpg', 'Home', 'Advanced market node optimization for the Home sector. Tier 3 authorization. Unit #9.', 3),
('Vector Prime 894 - Senior', '/items/premium/best-bluetooth-speakers-for-bass.png', 'Beauty', 'Advanced market node optimization for the Beauty sector. Tier 3 authorization. Unit #10.', 3),
('Zenith Peak 676 - Senior', '/items/premium/Denims_DiamondsStore-2024-08-07T160458.437.png', 'Electronics', 'Advanced market node optimization for the Electronics sector. Tier 3 authorization. Unit #11.', 3),
('Origin Base 713 - Senior', '/items/premium/rsz_11img_0600.jpg', 'Beauty', 'Advanced market node optimization for the Beauty sector. Tier 3 authorization. Unit #12.', 3),
('Spectrum Glow 990 - Senior', '/items/premium/led-tv-500x500.jpeg', 'Beauty', 'Advanced market node optimization for the Beauty sector. Tier 3 authorization. Unit #13.', 3),
('Peak Precision 183 - Senior', '/items/premium/151235983-111490335-1605098257.jpg', 'Luxury', 'Advanced market node optimization for the Luxury sector. Tier 3 authorization. Unit #14.', 3),
('Zenith Peak 859 - Senior', '/items/premium/5251M_1_HD.png', 'Strategic', 'Advanced market node optimization for the Strategic sector. Tier 3 authorization. Unit #15.', 3),
('Pure Silk 145 - Senior', '/items/premium/1000_F_724001883_roW5kbUlgXdSVPE7U3GJaW0bkyjjTUxd.jpg', 'Finance', 'Advanced market node optimization for the Finance sector. Tier 3 authorization. Unit #16.', 3),
('Grand Master 909 - Senior', '/items/premium/0605d0004c2b641ac89cef189898e983.jpg', 'Strategic', 'Advanced market node optimization for the Strategic sector. Tier 3 authorization. Unit #17.', 3),
('Steel Guard 588 - Senior', '/items/premium/the_definitive_guide_to_luxury_dining_tables_29_08_2023_01.jpg', 'Automotive', 'Advanced market node optimization for the Automotive sector. Tier 3 authorization. Unit #18.', 3),
('Vector Prime 661 - Senior', '/items/premium/355861094_270460518996981_8374521648662325660_n.jpg', 'Strategic', 'Advanced market node optimization for the Strategic sector. Tier 3 authorization. Unit #19.', 3),
('Retro Vibe 834 - Senior', '/items/premium/301015000000087_1.jpg', 'Automotive', 'Advanced market node optimization for the Automotive sector. Tier 3 authorization. Unit #20.', 3),
('Horizon Vista 686 - Senior', '/items/premium/car-battery.jpg', 'Electronics', 'Advanced market node optimization for the Electronics sector. Tier 3 authorization. Unit #21.', 3),
('Apex Prime Edition 950 - Senior', '/items/premium/interior-of-a-home-laundry-in-flat-doodle-style-wardrobe-washing-machine-ironing-board-iron-clothes-hanger-laundry-and-cleaning-products-vector-2RA2XJ1.jpg', 'Electronics', 'Advanced market node optimization for the Electronics sector. Tier 3 authorization. Unit #22.', 3),
('Grand Master 976 - Senior', '/items/premium/Car-Automotive-Vehicle-Battery-Lithium-Ion-Automotive-Start-Stop-Batteries-12V-45ah-60ah-75ah.jpg', 'Home', 'Advanced market node optimization for the Home sector. Tier 3 authorization. Unit #23.', 3),
('Quantum Series X 780 - Senior', '/items/premium/8ee4b931-4aab-410f-a8f7-70f2833b9456.jpg', 'Home', 'Advanced market node optimization for the Home sector. Tier 3 authorization. Unit #24.', 3),
('Premium Executive Suite 237 - Senior', '/items/premium/NIKE+V5+RNR-007.png', 'Luxury', 'Advanced market node optimization for the Luxury sector. Tier 3 authorization. Unit #25.', 3),
('Modern Era 707 - Senior', '/items/premium/AIR+FORCE+1+(GS)-004.png', 'Fashion', 'Advanced market node optimization for the Fashion sector. Tier 3 authorization. Unit #26.', 3),
('Nova Star 585 - Senior', '/items/premium/664e6e91-0431-4a11-b955-bca216d07b06.0e3ff394a3443598553b6af03c09013f.jpeg', 'Beauty', 'Advanced market node optimization for the Beauty sector. Tier 3 authorization. Unit #27.', 3),
('Nebula Smart Node 773 - Senior', '/items/premium/W+NIKE+DUNK+LOW-001.png', 'Luxury', 'Advanced market node optimization for the Luxury sector. Tier 3 authorization. Unit #28.', 3),
('Oasis Mist 518 - Senior', '/items/premium/SBWNEWYORK20Ecom1_2_360x.png', 'Health', 'Advanced market node optimization for the Health sector. Tier 3 authorization. Unit #29.', 3),
('Fusion Core 118 - Senior', '/items/premium/1000_F_468577805_ncRnLHMVnNS1csMw8IdwgN9Ml9UwjV3L.jpg', 'Luxury', 'Advanced market node optimization for the Luxury sector. Tier 3 authorization. Unit #30.', 3),
('Nova Star 727 - Senior', '/items/premium/dhjs5-rTp-tKYwmSP5LiA.jpg', 'Finance', 'Advanced market node optimization for the Finance sector. Tier 3 authorization. Unit #31.', 3),
('Diamond Edge 904 - Senior', '/items/premium/Car_Engine_v2_000.jpg370b8fa5-5919-42c3-9165-de23f0909b7cOriginal.jpg', 'Fashion', 'Advanced market node optimization for the Fashion sector. Tier 3 authorization. Unit #32.', 3),
('Matrix Link 946 - Senior', '/items/premium/Branding-1-300x300.png', 'Health', 'Advanced market node optimization for the Health sector. Tier 3 authorization. Unit #33.', 3),
('Titan Core 608 - Senior', '/items/premium/WanderingCreek_ValerieTudor_Kitchen_2-3.jpeg', 'Fashion', 'Advanced market node optimization for the Fashion sector. Tier 3 authorization. Unit #34.', 3),
('Horizon Plus 664 - Senior', '/items/premium/double-basin-stainless-steel-farmhouse-kitchen-sink-navy-blue-kitchen-cabinets-lower-white-upper-cabinets-two-tone-white-countertops-modern.png', 'Luxury', 'Advanced market node optimization for the Luxury sector. Tier 3 authorization. Unit #35.', 3),
('Horizon Plus 585 - Senior', '/items/premium/NIKE+ZOOM+VOMERO+5.png', 'Home', 'Advanced market node optimization for the Home sector. Tier 3 authorization. Unit #36.', 3),
('Gold Standard 482 - Senior', '/items/premium/11643005_1.jpg', 'Electronics', 'Advanced market node optimization for the Electronics sector. Tier 3 authorization. Unit #37.', 3),
('Horizon Vista 611 - Senior', '/items/premium/ChatGPT-Image-Feb-26-2026-12_32_00-PM.png', 'Strategic', 'Advanced market node optimization for the Strategic sector. Tier 3 authorization. Unit #38.', 3),
('Flux Capacitor 316 - Senior', '/items/premium/pijama-frida-mariposas-rosa-antique.jpg', 'Fashion', 'Advanced market node optimization for the Fashion sector. Tier 3 authorization. Unit #39.', 3),
('Oasis Mist 461 - Senior', '/items/premium/5508eb6c80e18-ghk-0413-prescription-glasses-display-s2.jpg', 'Automotive', 'Advanced market node optimization for the Automotive sector. Tier 3 authorization. Unit #40.', 3),
('Legacy Gold 622 - Senior', '/items/premium/680b4630-fdad-403c-8da2-f726b43e87a9.1c3f4b30a48e25ba15a45d49418107e7.jpeg', 'Strategic', 'Advanced market node optimization for the Strategic sector. Tier 3 authorization. Unit #41.', 3),
('Chrono Master 348 - Senior', '/items/premium/viziosmartcast.jpg', 'Health', 'Advanced market node optimization for the Health sector. Tier 3 authorization. Unit #42.', 3),
('Catalyst Pro 421 - Senior', '/items/premium/NIKE+V5+RNR-003.png', 'Strategic', 'Advanced market node optimization for the Strategic sector. Tier 3 authorization. Unit #43.', 3),
('Echo Pulse 902 - Senior', '/items/premium/cPug7uS9GsvHmQv7ES88C.jpg', 'Electronics', 'Advanced market node optimization for the Electronics sector. Tier 3 authorization. Unit #44.', 3),
('Echo Pulse 627 - Senior', '/items/premium/sea-tier-3-hamilton-beach-digital-programmable-rice-cooker-ahuang-127-4920faa05169437796e2877ad1da0613.jpeg', 'Electronics', 'Advanced market node optimization for the Electronics sector. Tier 3 authorization. Unit #45.', 3),
('Gold Standard 300 - Senior', '/items/premium/learn-why-enrolling-in-an-fsa-is-a-must-for-glasses-and-contact-lens-wearers-ss-1216420312-web-16x8.jpg', 'Fashion', 'Advanced market node optimization for the Fashion sector. Tier 3 authorization. Unit #46.', 3),
('Premium Executive Suite 447 - Senior', '/items/premium/61Zm6dZB4ZL._AC_SL1500_.jpg', 'Electronics', 'Advanced market node optimization for the Electronics sector. Tier 3 authorization. Unit #47.', 3),
('Fusion Core 740 - Senior', '/items/premium/pijama-velour-spiderman-azul.jpg', 'Beauty', 'Advanced market node optimization for the Beauty sector. Tier 3 authorization. Unit #48.', 3),
('Solaris Ultra 828 - Senior', '/items/premium/NIKE+VOMERO+18+(GS)-001.png', 'Health', 'Advanced market node optimization for the Health sector. Tier 3 authorization. Unit #49.', 3),
('Nebula Smart Node 681 - Senior', '/items/premium/1_7f803d62695f6577ef5f78d113e87f9f.jpg', 'Health', 'Advanced market node optimization for the Health sector. Tier 3 authorization. Unit #50.', 3),
('Titan Core 487 - Elite', '/items/premium/15-001.jpg', 'Health', 'Advanced market node optimization for the Health sector. Tier 4 authorization. Unit #1.', 4),
('Pulse Beat 364 - Elite', '/items/premium/cucine-lube-blog-articolo-frigorifero_1.jpg', 'Strategic', 'Advanced market node optimization for the Strategic sector. Tier 4 authorization. Unit #2.', 4),
('Orbit One 642 - Elite', '/items/premium/LED-SHV32108.jpg', 'Strategic', 'Advanced market node optimization for the Strategic sector. Tier 4 authorization. Unit #3.', 4),
('Premium Executive Suite 671 - Elite', '/items/premium/large_art-deco-wardrobe-sku36485295_0-002.jpg', 'Strategic', 'Advanced market node optimization for the Strategic sector. Tier 4 authorization. Unit #4.', 4),
('Origin Base 551 - Elite', '/items/premium/Marble-Finish_Rectangular_Dining_Table_Set_with_Padded_Chairs.jpg', 'Health', 'Advanced market node optimization for the Health sector. Tier 4 authorization. Unit #5.', 4),
('Nebula Smart Node 780 - Elite', '/items/premium/1764407237_63e41bb67048271a39c7.png', 'Automotive', 'Advanced market node optimization for the Automotive sector. Tier 4 authorization. Unit #6.', 4),
('Nebula Smart Node 560 - Elite', '/items/premium/VOMERO+5+(GS)-006.png', 'Luxury', 'Advanced market node optimization for the Luxury sector. Tier 4 authorization. Unit #7.', 4),
('Infinity Loop 273 - Elite', '/items/premium/JORDAN+4+RETRO+OG+(TD)-001.png', 'Strategic', 'Advanced market node optimization for the Strategic sector. Tier 4 authorization. Unit #8.', 4),
('Fusion Core 173 - Elite', '/items/premium/VOMERO+5+(GS).png', 'Beauty', 'Advanced market node optimization for the Beauty sector. Tier 4 authorization. Unit #9.', 4),
('Catalyst Pro 723 - Elite', '/items/premium/BEST-CHEAP-GAMING-LAPTOPS-9197.jpg', 'Finance', 'Advanced market node optimization for the Finance sector. Tier 4 authorization. Unit #10.', 4),
('Luxe Crystal 777 - Elite', '/items/premium/AsRgmk3fLVA4r54uc8wume.jpg', 'Finance', 'Advanced market node optimization for the Finance sector. Tier 4 authorization. Unit #11.', 4),
('Chrono Master 605 - Elite', '/items/premium/headphones.png', 'Beauty', 'Advanced market node optimization for the Beauty sector. Tier 4 authorization. Unit #12.', 4),
('Prism Dynamic 678 - Elite', '/items/premium/farmhouse_sink_vs_undermount_sink.png', 'Beauty', 'Advanced market node optimization for the Beauty sector. Tier 4 authorization. Unit #13.', 4),
('Vector Prime 317 - Elite', '/items/premium/Mgr7dtRuVF3ahQekYBo6TR.jpeg', 'Electronics', 'Advanced market node optimization for the Electronics sector. Tier 4 authorization. Unit #14.', 4),
('Oasis Mist 979 - Elite', '/items/premium/style-dressing-table-with-mirror-in-cream-in-french-style-dressing-table-mirror.jpg', 'Luxury', 'Advanced market node optimization for the Luxury sector. Tier 4 authorization. Unit #15.', 4),
('Aura Glow 476 - Elite', '/items/premium/acoustic-guitar-close-up-D25YWN.jpg', 'Electronics', 'Advanced market node optimization for the Electronics sector. Tier 4 authorization. Unit #16.', 4),
('Velocity Max 215 - Elite', '/items/premium/oaQcRgQbnLRctZAmgzgBbA.jpg', 'Electronics', 'Advanced market node optimization for the Electronics sector. Tier 4 authorization. Unit #17.', 4),
('Cyber Core 638 - Elite', '/items/premium/NIKE+ZOOM+VOMERO+5-002.png', 'Home', 'Advanced market node optimization for the Home sector. Tier 4 authorization. Unit #18.', 4),
('Synapse Net 107 - Elite', '/items/premium/73f971c7-125a-4bc8-a015-872d0c82cec2.88363a7a28a6547fee6da2041d4f07d0.jpeg', 'Fashion', 'Advanced market node optimization for the Fashion sector. Tier 4 authorization. Unit #19.', 4),
('Velocity Max 167 - Elite', '/items/premium/W+NIKE+AIR+MAX+95+BIG+BUBBLE-002.png', 'Fashion', 'Advanced market node optimization for the Fashion sector. Tier 4 authorization. Unit #20.', 4),
('Horizon Plus 289 - Elite', '/items/premium/productgroupshot_imagesofbeautyproducts_8.jpg', 'Strategic', 'Advanced market node optimization for the Strategic sector. Tier 4 authorization. Unit #21.', 4),
('Retro Vibe 780 - Elite', '/items/premium/1743f3e0ebb44d4a16a706f87b8de11d.jpg', 'Beauty', 'Advanced market node optimization for the Beauty sector. Tier 4 authorization. Unit #22.', 4),
('Omni Vision Pro 519 - Elite', '/items/premium/how-to-clean-your-tv-screen-in-6-easy-steps-pc.jpeg', 'Beauty', 'Advanced market node optimization for the Beauty sector. Tier 4 authorization. Unit #23.', 4),
('Apex Prime Edition 132 - Elite', '/items/premium/NIKE+VOMERO+18-004.png', 'Fashion', 'Advanced market node optimization for the Fashion sector. Tier 4 authorization. Unit #24.', 4),
('Matrix Link 182 - Elite', '/items/premium/mens-diamond-ring.jpg', 'Luxury', 'Advanced market node optimization for the Luxury sector. Tier 4 authorization. Unit #25.', 4),
('Premium Executive Suite 471 - Elite', '/items/premium/washing-machine-stand-1000x1000.jpg', 'Finance', 'Advanced market node optimization for the Finance sector. Tier 4 authorization. Unit #26.', 4),
('Nova Star 299 - Elite', '/items/premium/O1CN01l320281XK4rtMAHzv_3899502904-0-cib_09d40268-7009-4200-bb66-5d2f6effa0eb.jpg', 'Home', 'Advanced market node optimization for the Home sector. Tier 4 authorization. Unit #27.', 4),
('Matrix Link 670 - Elite', '/items/premium/714cZTF0ZAS._AC_SL1500_.jpg', 'Beauty', 'Advanced market node optimization for the Beauty sector. Tier 4 authorization. Unit #28.', 4),
('Fusion Core 581 - Elite', '/items/premium/e4.JPG', 'Luxury', 'Advanced market node optimization for the Luxury sector. Tier 4 authorization. Unit #29.', 4),
('Horizon Vista 413 - Elite', '/items/premium/1239375-wd1-final-render-1661760274-rAbLM.jpg', 'Finance', 'Advanced market node optimization for the Finance sector. Tier 4 authorization. Unit #30.', 4),
('Synapse Net 718 - Elite', '/items/premium/6.jfif', 'Finance', 'Advanced market node optimization for the Finance sector. Tier 4 authorization. Unit #31.', 4),
('Solaris Ultra 346 - Elite', '/items/premium/cooking-spicy-thai-basil-chicken-in-pan-6779590.jpg', 'Electronics', 'Advanced market node optimization for the Electronics sector. Tier 4 authorization. Unit #32.', 4),
('Apex Prime Edition 818 - Elite', '/items/premium/shot-makeup-products-arrange-lipstick-blush-eyeshadow-visually-pleasing-way_629685-1870.jpg', 'Fashion', 'Advanced market node optimization for the Fashion sector. Tier 4 authorization. Unit #33.', 4),
('Grand Master 400 - Elite', '/items/premium/0ef17740-8491-47d1-b9cd-301bff9d147a.e753d8eddad9c60655c97a129f26e35c.jpeg', 'Health', 'Advanced market node optimization for the Health sector. Tier 4 authorization. Unit #34.', 4),
('Arc Light 195 - Elite', '/items/premium/074c418fc0c1f1267f252cfcd17d850b.jpg', 'Finance', 'Advanced market node optimization for the Finance sector. Tier 4 authorization. Unit #35.', 4),
('Legacy Gold 564 - Elite', '/items/premium/fpd-32-inch-smart-tv-google-tv-frameless-tv-lcd-tv-dolby-hdr-10-support-160747.png', 'Health', 'Advanced market node optimization for the Health sector. Tier 4 authorization. Unit #36.', 4),
('Vector Prime 576 - Elite', '/items/premium/dmitriy-m-drums002.jpg', 'Strategic', 'Advanced market node optimization for the Strategic sector. Tier 4 authorization. Unit #37.', 4),
('Vector Prime 635 - Elite', '/items/premium/AIR+MAX+90+(GS).png', 'Luxury', 'Advanced market node optimization for the Luxury sector. Tier 4 authorization. Unit #38.', 4),
('Oasis Mist 147 - Elite', '/items/premium/AIR+FORCE+1+BG-001.png', 'Finance', 'Advanced market node optimization for the Finance sector. Tier 4 authorization. Unit #39.', 4),
('Flux Capacitor 915 - Elite', '/items/premium/51rdxIdtu6L._SL500_.jpg', 'Home', 'Advanced market node optimization for the Home sector. Tier 4 authorization. Unit #40.', 4),
('Oasis Mist 957 - Elite', '/items/premium/Joystick.jpg', 'Strategic', 'Advanced market node optimization for the Strategic sector. Tier 4 authorization. Unit #41.', 4),
('Orbit One 270 - Elite', '/items/premium/71FoxxBhs8L._SL1500_.jpg', 'Automotive', 'Advanced market node optimization for the Automotive sector. Tier 4 authorization. Unit #42.', 4),
('Prism Dynamic 945 - Elite', '/items/premium/category_images_washingmachine_compressed__43074.original.jpg', 'Automotive', 'Advanced market node optimization for the Automotive sector. Tier 4 authorization. Unit #43.', 4),
('Luxe Crystal 974 - Elite', '/items/premium/il_1080xN.3914739613_2vkc.jpg', 'Luxury', 'Advanced market node optimization for the Luxury sector. Tier 4 authorization. Unit #44.', 4),
('Grand Master 679 - Elite', '/items/premium/40d4a66ea3c509e3b1ca6f1ec66785d9.jpg', 'Beauty', 'Advanced market node optimization for the Beauty sector. Tier 4 authorization. Unit #45.', 4),
('Grand Master 511 - Elite', '/items/premium/Security-Door-Hardware.png', 'Luxury', 'Advanced market node optimization for the Luxury sector. Tier 4 authorization. Unit #46.', 4),
('Vector Prime 110 - Elite', '/items/premium/studio-microphone-setup-stockcake-005.jpg', 'Electronics', 'Advanced market node optimization for the Electronics sector. Tier 4 authorization. Unit #47.', 4),
('Velocity Max 915 - Elite', '/items/premium/commercialDoorsAndFrames.jpg', 'Health', 'Advanced market node optimization for the Health sector. Tier 4 authorization. Unit #48.', 4),
('Quantum Series X 418 - Elite', '/items/premium/maxresdefault.jpg', 'Automotive', 'Advanced market node optimization for the Automotive sector. Tier 4 authorization. Unit #49.', 4),
('Titan Core 685 - Elite', '/items/premium/bass-electric-guitar-with-four-strings-closeup-detail-of-popular-rock-musical-instrument-close-view-of-element-of-wooden-textured-bass-vintage-macr-2MCB755.jpg', 'Luxury', 'Advanced market node optimization for the Luxury sector. Tier 4 authorization. Unit #50.', 4),
('Omni Vision Pro 354 - Elite', '/items/premium/il_fullxfull.2121599933_surk.jpg', 'Automotive', 'Advanced market node optimization for the Automotive sector. Tier 4 authorization. Unit #51.', 4),
('Cyber Core 567 - Elite', '/items/premium/opera-calliope-dressing-table-mirror-buy-online-at-luxdeco-throughout-contemporary-dressing-table-mirrors.jpg', 'Health', 'Advanced market node optimization for the Health sector. Tier 4 authorization. Unit #52.', 4),
('Origin Base 589 - Elite', '/items/premium/SUITS201210244280.jpg', 'Home', 'Advanced market node optimization for the Home sector. Tier 4 authorization. Unit #53.', 4),
('Classic Chic 467 - Elite', '/items/premium/no-brand_jaket-pria-casual-distro-jaket-bomber-pria-terbaru_full01.jpg', 'Automotive', 'Advanced market node optimization for the Automotive sector. Tier 4 authorization. Unit #54.', 4),
('Arc Light 181 - Elite', '/items/premium/acoustic-guitar-close-up-D25YWC.jpg', 'Fashion', 'Advanced market node optimization for the Fashion sector. Tier 4 authorization. Unit #55.', 4),
('Omni Vision Pro 699 - Ultimate', '/items/premium/Product-Selection_w-eyeglasses.jpg', 'Health', 'Advanced market node optimization for the Health sector. Tier 5 authorization. Unit #1.', 5),
('Spectrum Glow 299 - Ultimate', '/items/premium/811hGWxj1gL._AC_SL1500_.jpg', 'Automotive', 'Advanced market node optimization for the Automotive sector. Tier 5 authorization. Unit #2.', 5),
('Prime Focus 336 - Ultimate', '/items/premium/il_fullxfull.1963944214_m2wq.jpg', 'Electronics', 'Advanced market node optimization for the Electronics sector. Tier 5 authorization. Unit #3.', 5),
('Synapse Net 189 - Ultimate', '/items/premium/VOMERO+5+(GS)-001.png', 'Fashion', 'Advanced market node optimization for the Fashion sector. Tier 5 authorization. Unit #4.', 5),
('Legacy Gold 536 - Ultimate', '/items/premium/designer-water-closet-1000x1000.jpeg', 'Automotive', 'Advanced market node optimization for the Automotive sector. Tier 5 authorization. Unit #5.', 5),
('Vector Prime 274 - Ultimate', '/items/premium/6.jpg', 'Beauty', 'Advanced market node optimization for the Beauty sector. Tier 5 authorization. Unit #6.', 5),
('Diamond Edge 627 - Ultimate', '/items/premium/3_7736a591-8b43-4f13-be0c-1e4a87b18edc.jpg', 'Fashion', 'Advanced market node optimization for the Fashion sector. Tier 5 authorization. Unit #7.', 5),
('Vanguard Leather Bound 630 - Ultimate', '/items/premium/e021e189feeb4553913d67874fecadf2~.jpeg', 'Health', 'Advanced market node optimization for the Health sector. Tier 5 authorization. Unit #8.', 5),
('Apex Prime Edition 446 - Ultimate', '/items/premium/car-tire-product-photography_950558-12789.jpg', 'Strategic', 'Advanced market node optimization for the Strategic sector. Tier 5 authorization. Unit #9.', 5),
('Pulse Beat 560 - Ultimate', '/items/premium/car-battery-work.jpg', 'Automotive', 'Advanced market node optimization for the Automotive sector. Tier 5 authorization. Unit #10.', 5),
('Diamond Edge 609 - Ultimate', '/items/premium/fashionable-set-makeup-product-arranged-neatly-create-eyecatching-display-beauty-facial-essentials_984126-11539.jpg', 'Automotive', 'Advanced market node optimization for the Automotive sector. Tier 5 authorization. Unit #11.', 5),
('Prime Focus 393 - Ultimate', '/items/premium/il_fullxfull.2552631737_bnox.jpg', 'Fashion', 'Advanced market node optimization for the Fashion sector. Tier 5 authorization. Unit #12.', 5),
('Prism Dynamic 901 - Ultimate', '/items/premium/03v6gxxlsook.jpg', 'Fashion', 'Advanced market node optimization for the Fashion sector. Tier 5 authorization. Unit #13.', 5),
('Modern Era 572 - Ultimate', '/items/premium/W+NIKE+AIR+MAX+95+BIG+BUBBLE-001.png', 'Automotive', 'Advanced market node optimization for the Automotive sector. Tier 5 authorization. Unit #14.', 5),
('Prime Focus 456 - Ultimate', '/items/premium/HTB1kNvVa1H2gK0jSZJnq6yT1FXaZ.jpg', 'Finance', 'Advanced market node optimization for the Finance sector. Tier 5 authorization. Unit #15.', 5),
('Vanguard Leather Bound 950 - Ultimate', '/items/premium/ASUS-TUF-Gaming-A15-FA506NCG-AMD-Ryzen-7-7445HS-NVIDIA-GeForce-RTX-3050-With-4GB-Graphic-15.6-Gaming-Laptopd-7507.png', 'Home', 'Advanced market node optimization for the Home sector. Tier 5 authorization. Unit #16.', 5),
('Spectrum Glow 320 - Ultimate', '/items/premium/W+NIKE+VOMERO+PLUS.png', 'Electronics', 'Advanced market node optimization for the Electronics sector. Tier 5 authorization. Unit #17.', 5),
('Legacy Gold 835 - Ultimate', '/items/premium/selena-gomez-rare-beauty-t.jpg', 'Luxury', 'Advanced market node optimization for the Luxury sector. Tier 5 authorization. Unit #18.', 5),
('Nebula Smart Node 541 - Ultimate', '/items/premium/il_794xN.1277057015_anlg.jpg', 'Luxury', 'Advanced market node optimization for the Luxury sector. Tier 5 authorization. Unit #19.', 5),
('Grand Master 728 - Ultimate', '/items/premium/Screenshot_2023-08-05_at_2.52.07_PM.png', 'Beauty', 'Advanced market node optimization for the Beauty sector. Tier 5 authorization. Unit #20.', 5),
('Gold Standard 935 - Ultimate', '/items/premium/723f6e5411013289ab5450113d6ced21-stainless-steel-farmhouse-sink-farmhouse-sink-kitchen.jpg', 'Beauty', 'Advanced market node optimization for the Beauty sector. Tier 5 authorization. Unit #21.', 5),
('Chrono Master 603 - Ultimate', '/items/premium/modern_toilet.jpg', 'Beauty', 'Advanced market node optimization for the Beauty sector. Tier 5 authorization. Unit #22.', 5),
('Vanguard Leather Bound 257 - Ultimate', '/items/premium/Solo-Sauce-Pan.jpg', 'Strategic', 'Advanced market node optimization for the Strategic sector. Tier 5 authorization. Unit #23.', 5),
('Arc Light 842 - Ultimate', '/items/premium/Copy-of-Featured-Image-74.jpg', 'Finance', 'Advanced market node optimization for the Finance sector. Tier 5 authorization. Unit #24.', 5),
('Nova Star 417 - Ultimate', '/items/premium/Luxury-Bedroom-Furniture-Set.jpg', 'Home', 'Advanced market node optimization for the Home sector. Tier 5 authorization. Unit #25.', 5),
('Retro Vibe 960 - Ultimate', '/items/premium/pvc-sliding-wardrobe-1000x1000-001.jpg', 'Strategic', 'Advanced market node optimization for the Strategic sector. Tier 5 authorization. Unit #26.', 5),
('Origin Base 324 - Ultimate', '/items/premium/bass-speaker_480x480.jpg', 'Home', 'Advanced market node optimization for the Home sector. Tier 5 authorization. Unit #27.', 5),
('Nebula Smart Node 411 - Ultimate', '/items/premium/5.png', 'Electronics', 'Advanced market node optimization for the Electronics sector. Tier 5 authorization. Unit #28.', 5),
('Peak Precision 190 - Ultimate', '/items/premium/43-fhd-low-price-google-tv-online-kerala.png', 'Finance', 'Advanced market node optimization for the Finance sector. Tier 5 authorization. Unit #29.', 5),
('Luxe Crystal 376 - Ultimate', '/items/premium/dumbbells.png', 'Strategic', 'Advanced market node optimization for the Strategic sector. Tier 5 authorization. Unit #30.', 5),
('Titan Core 765 - Ultimate', '/items/premium/counterdepthfridges-2048px-fp-3x1-1.jpg', 'Home', 'Advanced market node optimization for the Home sector. Tier 5 authorization. Unit #31.', 5),
('Chrono Master 244 - Ultimate', '/items/premium/pv00927_01.jpg', 'Home', 'Advanced market node optimization for the Home sector. Tier 5 authorization. Unit #32.', 5),
('Pure Silk 287 - Ultimate', '/items/premium/81350d43-5e03-4a8d-b4b0-6ce84cc69510.png', 'Finance', 'Advanced market node optimization for the Finance sector. Tier 5 authorization. Unit #33.', 5),
('Origin Base 310 - Ultimate', '/items/premium/8799c968fb30982b85d6f716f1209eaa.jpg_720x720q80.jpg', 'Automotive', 'Advanced market node optimization for the Automotive sector. Tier 5 authorization. Unit #34.', 5),
('Fusion Core 419 - Ultimate', '/items/premium/din70-automotive-car-battery-1000x1000.jpg', 'Strategic', 'Advanced market node optimization for the Strategic sector. Tier 5 authorization. Unit #35.', 5),
('Fusion Core 838 - Ultimate', '/items/premium/1000_F_705106048_1HfGhDo9tupwE0aF0AToDZrmWMd7e9RN.jpg', 'Health', 'Advanced market node optimization for the Health sector. Tier 5 authorization. Unit #36.', 5),
('Chrono Master 339 - Ultimate', '/items/premium/dream-kit-bg-with-transition-1352px-2x.jpg', 'Finance', 'Advanced market node optimization for the Finance sector. Tier 5 authorization. Unit #37.', 5),
('Titan Core 511 - Ultimate', '/items/premium/e16d89a5142f4c0e26ac927ab2a42bf7.jpg', 'Electronics', 'Advanced market node optimization for the Electronics sector. Tier 5 authorization. Unit #38.', 5),
('Classic Chic 122 - Ultimate', '/items/premium/bridal-dresses-a-line-with-long-sleeves-lace-evalendel.jpg', 'Luxury', 'Advanced market node optimization for the Luxury sector. Tier 5 authorization. Unit #39.', 5),
('Cyber Core 571 - Ultimate', '/items/premium/il_fullxfull.3040775138_62xg.jpg', 'Electronics', 'Advanced market node optimization for the Electronics sector. Tier 5 authorization. Unit #40.', 5),
('Catalyst Pro 237 - Ultimate', '/items/premium/1009387.jpg', 'Fashion', 'Advanced market node optimization for the Fashion sector. Tier 5 authorization. Unit #41.', 5),
('Nebula Smart Node 278 - Ultimate', '/items/premium/premium-quality-designer-leather-hand-bag-500x500.jpeg', 'Fashion', 'Advanced market node optimization for the Fashion sector. Tier 5 authorization. Unit #42.', 5),
('Chrono Master 175 - Ultimate', '/items/premium/Diamond-Nexus-best-places-to-buy-engagement-rings-for-women.jpg', 'Luxury', 'Advanced market node optimization for the Luxury sector. Tier 5 authorization. Unit #43.', 5),
('Stellar Edge 213 - Ultimate', '/items/premium/the-men-thing-pack-of-5-alloy-pendants-with-24-inch-stainless-steel-chains-for-men-boys-1195367783_e536a2c0-0e6f-4740-bbb7-b3827ea01b27.png', 'Home', 'Advanced market node optimization for the Home sector. Tier 5 authorization. Unit #44.', 5),
('Grand Master 219 - Ultimate', '/items/premium/07DXYw0IPU4i8oPdnMnBeGr-4..v1684501793.jpg', 'Finance', 'Advanced market node optimization for the Finance sector. Tier 5 authorization. Unit #45.', 5),
('Omni Vision Pro 898 - Ultimate', '/items/premium/FFFFD1933-60S-Forno-Rizzuto-Built-In-Side-by-Side-Refrigerator-Freezer-lifestyle-1_522a8194-1301-487a-a0fc-6ca28c276f01.jpg', 'Health', 'Advanced market node optimization for the Health sector. Tier 5 authorization. Unit #46.', 5),
('Arc Light 511 - Ultimate', '/items/premium/The-8-Best-Lithium-Phosphate-Battery-Charger-for-Car-Applications-in-2026.jpg', 'Beauty', 'Advanced market node optimization for the Beauty sector. Tier 5 authorization. Unit #47.', 5),
('Element Zero 484 - Ultimate', '/items/premium/5a6e46f651ab4b08bf45a1deeae3d151~.jpeg', 'Beauty', 'Advanced market node optimization for the Beauty sector. Tier 5 authorization. Unit #48.', 5),
('Synapse Net 409 - Ultimate', '/items/premium/il_1140xN.2826236091_li52.jpg', 'Strategic', 'Advanced market node optimization for the Strategic sector. Tier 5 authorization. Unit #49.', 5),
('Vanguard Leather Bound 908 - Ultimate', '/items/premium/Screenshot_2024-11-08_173421_a49738dc-fe1e-4d5c-83b8-73a37851525b.png', 'Electronics', 'Advanced market node optimization for the Electronics sector. Tier 5 authorization. Unit #50.', 5),
('Retro Vibe 439 - Ultimate', '/items/premium/men-travel-bag-dark-blue.jpg', 'Health', 'Advanced market node optimization for the Health sector. Tier 5 authorization. Unit #51.', 5),
('Chrono Master 429 - Ultimate', '/items/premium/the-full-haircare-sethair-gift-sets-585241.jpg', 'Home', 'Advanced market node optimization for the Home sector. Tier 5 authorization. Unit #52.', 5),
('Horizon Plus 221 - Ultimate', '/items/premium/interstate-batteries-have-gotten-the-job-done-for-many-1740999867.jpg', 'Strategic', 'Advanced market node optimization for the Strategic sector. Tier 5 authorization. Unit #53.', 5),
('Oasis Mist 908 - Ultimate', '/items/premium/86286350-258c-44ca-a484-9c6bb6f40679.jpeg', 'Luxury', 'Advanced market node optimization for the Luxury sector. Tier 5 authorization. Unit #54.', 5),
('Legacy Gold 436 - Ultimate', '/items/premium/solo-swoosh-mens-full-zip-hoodie-8bKgZZ.png', 'Automotive', 'Advanced market node optimization for the Automotive sector. Tier 5 authorization. Unit #55.', 5),
('Solaris Ultra 557 - Ultimate', '/items/premium/5.jpg', 'Automotive', 'Advanced market node optimization for the Automotive sector. Tier 5 authorization. Unit #56.', 5),
('Zenith Peak 478 - Ultimate', '/items/premium/a91f7d1b-35c4-42c4-8980-54998e9187f6.89ba749b5d58acf4bd5b22b82b5f1511.jpeg', 'Health', 'Advanced market node optimization for the Health sector. Tier 5 authorization. Unit #57.', 5),
('Steel Guard 322 - Ultimate', '/items/premium/3_Large_Image_Text_RIght.jpg', 'Fashion', 'Advanced market node optimization for the Fashion sector. Tier 5 authorization. Unit #58.', 5),
('Vector Prime 171 - Ultimate', '/items/premium/f86e9c1ab8230a14fc3c7e450ebfb4c9b8cba4e7dad83e00cce6f92cdff8f0a3_4e9d79e8-a35d-49f1-93e2-75c1443abd05.jpg', 'Automotive', 'Advanced market node optimization for the Automotive sector. Tier 5 authorization. Unit #59.', 5),
('Oasis Mist 709 - Ultimate', '/items/premium/M+NK+TCH+FLC+FZ+WR+HOODIE.png', 'Health', 'Advanced market node optimization for the Health sector. Tier 5 authorization. Unit #60.', 5);