-- 1. SET FIRST USER TO ADMIN
UPDATE public.profiles 
SET role = 'admin' 
WHERE id = (SELECT id FROM public.profiles ORDER BY created_at ASC LIMIT 1);

-- 2. CLEAR PREVIOUS TASKS FOR LEVEL 1
DELETE FROM public.task_items WHERE level_id = 1;

-- 3. INSERT 120 DYNAMIC TASKS FOR LEVEL 1 (JUNIOR)
INSERT INTO public.task_items (title, image_url, category, description, level_id)
VALUES
('Stellar Edge - Batch 1', '/items/premium/Water-Closet-Toilet-Complete-Sets-of-Ceramic-Basin-and-Wc-for-Project-School-Hotel.jpg', 'Home', 'High-fidelity product optimization for Home segment. Item #1.', 1),
('Omni Vision Pro - Batch 2', '/items/premium/EverStart-Platinum-AGM-Automotive-Battery-Group-Size-35-12-Volt-minimum-640-CCA-100RC_c00784c0-86bc-4cb7-a021-c582e82ae180.30ca6c39ee1b356e559fd8ce442513c6.jpeg', 'Fashion', 'High-fidelity product optimization for Fashion segment. Item #2.', 1),
('Titan Core - Batch 3', '/items/premium/il_794xN.2468828350_fszi.jpg', 'Electronics', 'High-fidelity product optimization for Electronics segment. Item #3.', 1),
('Infinity Loop - Batch 4', '/items/premium/hcu7qaSdVdgm6-xxlarge.jpg', 'Luxury', 'High-fidelity product optimization for Luxury segment. Item #4.', 1),
('Legacy Gold - Batch 5', '/items/premium/FORCE+1+LOW+EASYON+(TD)-001.png', 'Home', 'High-fidelity product optimization for Home segment. Item #5.', 1),
('Vector Prime - Batch 6', '/items/premium/3_7736a591-8b43-4f13-be0c-1e4a87b18edc.jpg', 'Electronics', 'High-fidelity product optimization for Electronics segment. Item #6.', 1),
('Matrix Link - Batch 7', '/items/premium/TribeBlue1.jpg', 'Automotive', 'High-fidelity product optimization for Automotive segment. Item #7.', 1),
('Synapse Net - Batch 8', '/items/premium/M+NIKE+METCON+10-004.png', 'Home', 'High-fidelity product optimization for Home segment. Item #8.', 1),
('Origin Base - Batch 9', '/items/premium/b17c6e043f1879a5137a1e7ba3b0d56e.jpg', 'Fashion', 'High-fidelity product optimization for Fashion segment. Item #9.', 1),
('Chrono Master - Batch 10', '/items/premium/il_fullxfull.4085878843_pfd8.jpg', 'Luxury', 'High-fidelity product optimization for Luxury segment. Item #10.', 1),
('Infinity Loop - Batch 11', '/items/premium/8SBZLzkseEfV5gnLsJ7JUK.jpg', 'Finance', 'High-fidelity product optimization for Finance segment. Item #11.', 1),
('Chrono Master - Batch 12', '/items/premium/how-to-set-up-maono-microphone-1704957120.jpg', 'Fashion', 'High-fidelity product optimization for Fashion segment. Item #12.', 1),
('Omni Vision Pro - Batch 13', '/items/premium/Jaket-Bomber-Pria-Kasual-Serba-Hitam.jpg', 'Strategic', 'High-fidelity product optimization for Strategic segment. Item #13.', 1),
('Fusion Core - Batch 14', '/items/premium/2338.png', 'Automotive', 'High-fidelity product optimization for Automotive segment. Item #14.', 1),
('Horizon Plus - Batch 15', '/items/premium/counterdepthfridges-2048px-fp-3x1-1.jpg', 'Automotive', 'High-fidelity product optimization for Automotive segment. Item #15.', 1),
('Vector Prime - Batch 16', '/items/premium/img.20260224114638179273.jpg', 'Automotive', 'High-fidelity product optimization for Automotive segment. Item #16.', 1),
('Nova Star - Batch 17', '/items/premium/HTB1zpI7TMHqK1RjSZFPq6AwapXaO.jpg', 'Luxury', 'High-fidelity product optimization for Luxury segment. Item #17.', 1),
('Origin Base - Batch 18', '/items/premium/Artboard-1.png', 'Home', 'High-fidelity product optimization for Home segment. Item #18.', 1),
('Arc Light - Batch 19', '/items/premium/sportswear-t-shirt-FPcVXK.png', 'Electronics', 'High-fidelity product optimization for Electronics segment. Item #19.', 1),
('Origin Base - Batch 20', '/items/premium/Wall-mounted-water-closet.png', 'Electronics', 'High-fidelity product optimization for Electronics segment. Item #20.', 1),
('Nova Star - Batch 21', '/items/premium/ladies-pajama-1000x1000.jpg', 'Home', 'High-fidelity product optimization for Home segment. Item #21.', 1),
('Solaris Ultra - Batch 22', '/items/premium/no-brand_jaket-pria-casual-distro-jaket-bomber-pria-terbaru_full01.jpg', 'Luxury', 'High-fidelity product optimization for Luxury segment. Item #22.', 1),
('Origin Base - Batch 23', '/items/premium/7b34662ce6afcabc2b33382e5204bd5a.jpg', 'Home', 'High-fidelity product optimization for Home segment. Item #23.', 1),
('Premium Executive Suite - Batch 24', '/items/premium/2024-01_Jenns_Dining_Living-2155_1_-2_992533ce-1db4-4ceb-bbc1-1a66286d9011_1200x1200.jpg', 'Finance', 'High-fidelity product optimization for Finance segment. Item #24.', 1),
('Solaris Ultra - Batch 25', '/items/premium/32hs550g_front.jpg', 'Fashion', 'High-fidelity product optimization for Fashion segment. Item #25.', 1),
('Element Zero - Batch 26', '/items/premium/Artist-Inspired-Eyeglasses-Case-Van-Gogh-The-Starry-Night-Handmade-Satin-Glasses-Holder-with-Kiss-Clasp-Frame-4.jpg', 'Electronics', 'High-fidelity product optimization for Electronics segment. Item #26.', 1),
('Chrono Master - Batch 27', '/items/premium/gold-curved-diamond-chunky-stacked-wedding-rings.jpeg', 'Electronics', 'High-fidelity product optimization for Electronics segment. Item #27.', 1),
('Element Zero - Batch 28', '/items/premium/Amstrad-AM65UWGTA-WebOS-TV_front.jpg', 'Finance', 'High-fidelity product optimization for Finance segment. Item #28.', 1),
('Horizon Plus - Batch 29', '/items/premium/81kGL7h4vVL._AC_SL1500_.jpg', 'Home', 'High-fidelity product optimization for Home segment. Item #29.', 1),
('Nebula Smart Node - Batch 30', '/items/premium/NIKE+VOMERO+18+(GS)-001.png', 'Electronics', 'High-fidelity product optimization for Electronics segment. Item #30.', 1),
('Prism Dynamic - Batch 31', '/items/premium/235-500x500.jpg', 'Luxury', 'High-fidelity product optimization for Luxury segment. Item #31.', 1),
('Stellar Edge - Batch 32', '/items/premium/Why_Does_Everyone_Want_Farmhouse_Sink.jpg', 'Fashion', 'High-fidelity product optimization for Fashion segment. Item #32.', 1),
('Velocity Max - Batch 33', '/items/premium/Manufacturer-High-Quality-Custom-Sleepwear-Set-Organic-Bamboo-Pajamas-for-Women.jpg', 'Electronics', 'High-fidelity product optimization for Electronics segment. Item #33.', 1),
('Prism Dynamic - Batch 34', '/items/premium/O1CN01WdLZz028tTfLa4Hr4_!!6000000007990-0-tps-582-678.jpg', 'Fashion', 'High-fidelity product optimization for Fashion segment. Item #34.', 1),
('Nebula Smart Node - Batch 35', '/items/premium/BEST-32-IN-TV-3281-2x1-1.jpg', 'Luxury', 'High-fidelity product optimization for Luxury segment. Item #35.', 1),
('Premium Executive Suite - Batch 36', '/items/premium/664e6e91-0431-4a11-b955-bca216d07b06.0e3ff394a3443598553b6af03c09013f.jpeg', 'Home', 'High-fidelity product optimization for Home segment. Item #36.', 1),
('Solaris Ultra - Batch 37', '/items/premium/SI_90400_Avignon_Driftwood1.jpg', 'Automotive', 'High-fidelity product optimization for Automotive segment. Item #37.', 1),
('Premium Executive Suite - Batch 38', '/items/premium/M+NIKE+METCON+10-005.png', 'Strategic', 'High-fidelity product optimization for Strategic segment. Item #38.', 1),
('Nova Star - Batch 39', '/items/premium/how-to-choose-glasses.jpg', 'Fashion', 'High-fidelity product optimization for Fashion segment. Item #39.', 1),
('Echo Pulse - Batch 40', '/items/premium/ready-mens-dri-fit-short-sleeve-fitness-top-bc8lMz.png', 'Home', 'High-fidelity product optimization for Home segment. Item #40.', 1),
('Element Zero - Batch 41', '/items/premium/8-1-scaled.jpg', 'Luxury', 'High-fidelity product optimization for Luxury segment. Item #41.', 1),
('Quantum Series X - Batch 42', '/items/premium/SHORT-WEDDING-DRESSES-12.jpg', 'Strategic', 'High-fidelity product optimization for Strategic segment. Item #42.', 1),
('Catalyst Pro - Batch 43', '/items/premium/Tako.jpg', 'Home', 'High-fidelity product optimization for Home segment. Item #43.', 1),
('Vanguard Leather Bound - Batch 44', '/items/premium/LED-SHV32108.jpg', 'Luxury', 'High-fidelity product optimization for Luxury segment. Item #44.', 1),
('Vector Prime - Batch 45', '/items/premium/ed651f231d5e4509b12ca45243c90d6e~.jpeg', 'Fashion', 'High-fidelity product optimization for Fashion segment. Item #45.', 1),
('Arc Light - Batch 46', '/items/premium/6f7d5a465c7553835a408131d44766c7.jpg', 'Fashion', 'High-fidelity product optimization for Fashion segment. Item #46.', 1),
('Omni Vision Pro - Batch 47', '/items/premium/makeup-cosmetics.jpg', 'Finance', 'High-fidelity product optimization for Finance segment. Item #47.', 1),
('Velocity Max - Batch 48', '/items/premium/12-min-1669205837-gT5XU.jpg', 'Finance', 'High-fidelity product optimization for Finance segment. Item #48.', 1),
('Horizon Plus - Batch 49', '/items/premium/dNk5Bjf4zkkUpNApjD2MBM-1920-80.jpg', 'Fashion', 'High-fidelity product optimization for Fashion segment. Item #49.', 1),
('Vanguard Leather Bound - Batch 50', '/items/premium/Gold-Rings-PNG-File.png', 'Luxury', 'High-fidelity product optimization for Luxury segment. Item #50.', 1),
('Apex Prime Edition - Batch 51', '/items/premium/d4d016d9c585f21c8d426383f2bdfb23.jpg', 'Luxury', 'High-fidelity product optimization for Luxury segment. Item #51.', 1),
('Catalyst Pro - Batch 52', '/items/premium/category_images_washingmachine_compressed__43074.original.jpg', 'Luxury', 'High-fidelity product optimization for Luxury segment. Item #52.', 1),
('Titan Core - Batch 53', '/items/premium/close-up-of-acoustic-guitar-PX058E.jpg', 'Home', 'High-fidelity product optimization for Home segment. Item #53.', 1),
('Flux Capacitor - Batch 54', '/items/premium/IMG_2362.jpg', 'Electronics', 'High-fidelity product optimization for Electronics segment. Item #54.', 1),
('Prism Dynamic - Batch 55', '/items/premium/What-is-Smart-TV-Hero.jpg', 'Automotive', 'High-fidelity product optimization for Automotive segment. Item #55.', 1),
('Legacy Gold - Batch 56', '/items/premium/51E697AOe0L._SL500_.jpg', 'Electronics', 'High-fidelity product optimization for Electronics segment. Item #56.', 1),
('Horizon Plus - Batch 57', '/items/premium/il_1080xN.4317749898_e783.jpg', 'Fashion', 'High-fidelity product optimization for Fashion segment. Item #57.', 1),
('Infinity Loop - Batch 58', '/items/premium/fa7f3e80e73f4233fdaa59a81dca60ca.jpg', 'Automotive', 'High-fidelity product optimization for Automotive segment. Item #58.', 1),
('Catalyst Pro - Batch 59', '/items/premium/Water-Closet-Pink-Walls.jpg', 'Automotive', 'High-fidelity product optimization for Automotive segment. Item #59.', 1),
('Chrono Master - Batch 60', '/items/premium/wedding-after-party-dresses-69ab124607a6d.png', 'Home', 'High-fidelity product optimization for Home segment. Item #60.', 1),
('Fusion Core - Batch 61', '/items/premium/1600px_COLOURBOX3684969.jpeg', 'Finance', 'High-fidelity product optimization for Finance segment. Item #61.', 1),
('Vanguard Leather Bound - Batch 62', '/items/premium/razerlg-1760905858305.jpg', 'Luxury', 'High-fidelity product optimization for Luxury segment. Item #62.', 1),
('Omni Vision Pro - Batch 63', '/items/premium/r03629374_m_l.jpg', 'Home', 'High-fidelity product optimization for Home segment. Item #63.', 1),
('Catalyst Pro - Batch 64', '/items/premium/126-45_lg.jpg', 'Fashion', 'High-fidelity product optimization for Fashion segment. Item #64.', 1),
('Vanguard Leather Bound - Batch 65', '/items/premium/closeup-of-an-electric-guitar-ACY0AY.jpg', 'Home', 'High-fidelity product optimization for Home segment. Item #65.', 1),
('Arc Light - Batch 66', '/items/premium/door-hardware.jpg', 'Strategic', 'High-fidelity product optimization for Strategic segment. Item #66.', 1),
('Element Zero - Batch 67', '/items/premium/sportswear-club-fleece-mens-full-zip-hoodie-nR8tst-001.png', 'Fashion', 'High-fidelity product optimization for Fashion segment. Item #67.', 1),
('Origin Base - Batch 68', '/items/premium/product-500x500.jpeg', 'Fashion', 'High-fidelity product optimization for Fashion segment. Item #68.', 1),
('Pulse Beat - Batch 69', '/items/premium/designer-water-closet-500x500.jpg', 'Home', 'High-fidelity product optimization for Home segment. Item #69.', 1),
('Chrono Master - Batch 70', '/items/premium/Hg2-4-1024x1024.jpg', 'Electronics', 'High-fidelity product optimization for Electronics segment. Item #70.', 1),
('Solaris Ultra - Batch 71', '/items/premium/7c88d70e-61ed-48bf-b293-26ecb438cbd8.666d734980348dd07c196eda6cc0ef2f.jpeg', 'Home', 'High-fidelity product optimization for Home segment. Item #71.', 1),
('Chrono Master - Batch 72', '/items/premium/f2e74f286fd61cfc8fcae22f3a63f9ef.jpg', 'Automotive', 'High-fidelity product optimization for Automotive segment. Item #72.', 1),
('Catalyst Pro - Batch 73', '/items/premium/68CA7A8F-2DC6-416E-A3E4-C906C3E64164.jpg', 'Luxury', 'High-fidelity product optimization for Luxury segment. Item #73.', 1),
('Stellar Edge - Batch 74', '/items/premium/opera-calliope-dressing-table-mirror-buy-online-at-luxdeco-throughout-contemporary-dressing-table-mirrors.jpg', 'Automotive', 'High-fidelity product optimization for Automotive segment. Item #74.', 1),
('Element Zero - Batch 75', '/items/premium/makeup-products-studio-shot-cosmetics-studio-background-floating-eye-shadows-lipstick-closeup-shot_723234-5471.jpg', 'Home', 'High-fidelity product optimization for Home segment. Item #75.', 1),
('Titan Core - Batch 76', '/items/premium/vinci-mens-orange-three-piece-suit-orange-windowpane-plaid-3pc-formal-suit-for-wedding-church-and-business-halloween-color-4.jpg', 'Electronics', 'High-fidelity product optimization for Electronics segment. Item #76.', 1),
('Prism Dynamic - Batch 77', '/items/premium/studio-microphone-setup-stockcake-005.jpg', 'Automotive', 'High-fidelity product optimization for Automotive segment. Item #77.', 1),
('Infinity Loop - Batch 78', '/items/premium/aa4d81007a3718a69ad286af53c30c33-apron-sink-kitchen-drop-in-kitchen-sink-001.jpg', 'Fashion', 'High-fidelity product optimization for Fashion segment. Item #78.', 1),
('Echo Pulse - Batch 79', '/items/premium/Bags_Slides%201_0014_NEW-PROD%20(2).jpg', 'Luxury', 'High-fidelity product optimization for Luxury segment. Item #79.', 1),
('Zenith Peak - Batch 80', '/items/premium/sauce_pan_2.jpg', 'Home', 'High-fidelity product optimization for Home segment. Item #80.', 1),
('Orbit One - Batch 81', '/items/premium/stainless-steel-farmhouse-sink.jpg', 'Finance', 'High-fidelity product optimization for Finance segment. Item #81.', 1),
('Apex Prime Edition - Batch 82', '/items/premium/jbl-flip-5-review-waterproof-portable-bluetooth-speaker-1024x1024.jpg', 'Automotive', 'High-fidelity product optimization for Automotive segment. Item #82.', 1),
('Infinity Loop - Batch 83', '/items/premium/WMNS+AIR+FORCE+1+'07-001.png', 'Electronics', 'High-fidelity product optimization for Electronics segment. Item #83.', 1),
('Apex Prime Edition - Batch 84', '/items/premium/WanderingCreek_ValerieTudor_Kitchen_2-3.jpeg', 'Strategic', 'High-fidelity product optimization for Strategic segment. Item #84.', 1),
('Quantum Series X - Batch 85', '/items/premium/13-001.jpg', 'Automotive', 'High-fidelity product optimization for Automotive segment. Item #85.', 1),
('Matrix Link - Batch 86', '/items/premium/61jPanyNvFL._AC_SL1500_.jpg', 'Automotive', 'High-fidelity product optimization for Automotive segment. Item #86.', 1),
('Nebula Smart Node - Batch 87', '/items/premium/laptop.png', 'Finance', 'High-fidelity product optimization for Finance segment. Item #87.', 1),
('Omni Vision Pro - Batch 88', '/items/premium/electric-guitar-closeup-2BJ7WXN.jpg', 'Finance', 'High-fidelity product optimization for Finance segment. Item #88.', 1),
('Nebula Smart Node - Batch 89', '/items/premium/hyperx_cloud_alpha_wireless_1_main_9b9cead0-6024-4e71-96b0-31628b1d9485.jpg', 'Home', 'High-fidelity product optimization for Home segment. Item #89.', 1),
('Premium Executive Suite - Batch 90', '/items/premium/Full-Kitchen-Angle_B36CL80SNS_1-1200x864.jpg', 'Finance', 'High-fidelity product optimization for Finance segment. Item #90.', 1),
('Prism Dynamic - Batch 91', '/items/premium/vad716-sw_front_gal.jpg', 'Electronics', 'High-fidelity product optimization for Electronics segment. Item #91.', 1),
('Flux Capacitor - Batch 92', '/items/premium/C7010-S_102.jpg', 'Finance', 'High-fidelity product optimization for Finance segment. Item #92.', 1),
('Apex Prime Edition - Batch 93', '/items/premium/M+NK+TCH+FLC+FZ+WR+HOODIE.png', 'Automotive', 'High-fidelity product optimization for Automotive segment. Item #93.', 1),
('Vanguard Leather Bound - Batch 94', '/items/premium/1_7f803d62695f6577ef5f78d113e87f9f.jpg', 'Finance', 'High-fidelity product optimization for Finance segment. Item #94.', 1),
('Quantum Series X - Batch 95', '/items/premium/MiniOven_Ecom_10.jpg', 'Fashion', 'High-fidelity product optimization for Fashion segment. Item #95.', 1),
('Nebula Smart Node - Batch 96', '/items/premium/M+NK+TCH+FLC+FZ+WR+HOODIE-001.png', 'Fashion', 'High-fidelity product optimization for Fashion segment. Item #96.', 1),
('Matrix Link - Batch 97', '/items/premium/5508eb6c80e18-ghk-0413-prescription-glasses-display-s2.jpg', 'Home', 'High-fidelity product optimization for Home segment. Item #97.', 1),
('Zenith Peak - Batch 98', '/items/premium/JORDAN+1+RETRO+HIGH+OG+(PS)-001.png', 'Home', 'High-fidelity product optimization for Home segment. Item #98.', 1),
('Catalyst Pro - Batch 99', '/items/premium/zline-professional-stainless-steel-white-matte-wall-oven-WAS-WM-30-hero.jpg', 'Automotive', 'High-fidelity product optimization for Automotive segment. Item #99.', 1),
('Apex Prime Edition - Batch 100', '/items/premium/Screenshot_2025-04-08_091244.png', 'Finance', 'High-fidelity product optimization for Finance segment. Item #100.', 1),
('Chrono Master - Batch 101', '/items/premium/1000_F_871829576_zyY0lsYCMHj8VXAGI6cOTJObg4ZNkrnp.jpg', 'Fashion', 'High-fidelity product optimization for Fashion segment. Item #101.', 1),
('Infinity Loop - Batch 102', '/items/premium/M+NIKE+METCON+10-001.png', 'Home', 'High-fidelity product optimization for Home segment. Item #102.', 1),
('Solaris Ultra - Batch 103', '/items/premium/2023-soundbar-buying-guide-what-is-a-soundbar-f00-mo.jpg', 'Fashion', 'High-fidelity product optimization for Fashion segment. Item #103.', 1),
('Chrono Master - Batch 104', '/items/premium/M+NIKE+METCON+10.png', 'Electronics', 'High-fidelity product optimization for Electronics segment. Item #104.', 1),
('Aura Glow - Batch 105', '/items/premium/A0020Y_AAGRB_1000_001_088_0000_Light.jpg', 'Luxury', 'High-fidelity product optimization for Luxury segment. Item #105.', 1),
('Vanguard Leather Bound - Batch 106', '/items/premium/arenaev_001.jpg', 'Automotive', 'High-fidelity product optimization for Automotive segment. Item #106.', 1),
('Arc Light - Batch 107', '/items/premium/studio-microphone-setup-stockcake-001.jpg', 'Finance', 'High-fidelity product optimization for Finance segment. Item #107.', 1),
('Pulse Beat - Batch 108', '/items/premium/1652954172c7ea02c27095102bc0cfebc0468d8189.jpg', 'Luxury', 'High-fidelity product optimization for Luxury segment. Item #108.', 1),
('Titan Core - Batch 109', '/items/premium/11+-+Piece+Non-Stick+Aluminum+Cookware+Set.jpg', 'Finance', 'High-fidelity product optimization for Finance segment. Item #109.', 1),
('Legacy Gold - Batch 110', '/items/premium/sportswear-sport-essentials-mens-allover-print-pullover-hoodie-wRTRl3.png', 'Electronics', 'High-fidelity product optimization for Electronics segment. Item #110.', 1),
('Quantum Series X - Batch 111', '/items/premium/WMNS+AIR+JORDAN+1+RETRO+HI+OG-001.png', 'Finance', 'High-fidelity product optimization for Finance segment. Item #111.', 1),
('Prism Dynamic - Batch 112', '/items/premium/screenshot-20220628-220937-amazon-500x500.jpg', 'Fashion', 'High-fidelity product optimization for Fashion segment. Item #112.', 1),
('Arc Light - Batch 113', '/items/premium/din70-automotive-car-battery-1000x1000.jpg', 'Home', 'High-fidelity product optimization for Home segment. Item #113.', 1),
('Pulse Beat - Batch 114', '/items/premium/khvqagcgbnbqmo66ngao.jpg', 'Fashion', 'High-fidelity product optimization for Fashion segment. Item #114.', 1),
('Premium Executive Suite - Batch 115', '/items/premium/FFFFD1933-60S-Forno-Rizzuto-Built-In-Side-by-Side-Refrigerator-Freezer-lifestyle-1_522a8194-1301-487a-a0fc-6ca28c276f01.jpg', 'Finance', 'High-fidelity product optimization for Finance segment. Item #115.', 1),
('Flux Capacitor - Batch 116', '/items/premium/71W16PYMaTL._AC_SL1500_.jpg', 'Fashion', 'High-fidelity product optimization for Fashion segment. Item #116.', 1),
('Quantum Series X - Batch 117', '/items/premium/1000_F_825008575_3kXpIgOuA0Px2peaHm8Zol7kdlBb7XbY.jpg', 'Finance', 'High-fidelity product optimization for Finance segment. Item #117.', 1),
('Matrix Link - Batch 118', '/items/premium/il_fullxfull.6108533211_irgp.jpg', 'Finance', 'High-fidelity product optimization for Finance segment. Item #118.', 1),
('Legacy Gold - Batch 119', '/items/premium/studio-microphone-setup-stockcake-002.jpg', 'Automotive', 'High-fidelity product optimization for Automotive segment. Item #119.', 1),
('Orbit One - Batch 120', '/items/premium/Bags_Slides%201_0039_BV.jpg', 'Strategic', 'High-fidelity product optimization for Strategic segment. Item #120.', 1);